// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantilla_Base.Data;

#nullable disable

namespace Plantilla_Base.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527023001_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Auditoria", b =>
                {
                    b.Property<int>("Id_Auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Auditoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioCreaId_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificaId_Usuario")
                        .HasColumnType("integer");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Auditoria");

                    b.HasIndex("UsuarioCreaId_Usuario");

                    b.HasIndex("UsuarioModificaId_Usuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Dominios", b =>
                {
                    b.Property<int>("Id_Dominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Dominio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Padre")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Crea")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int?>("PadreId_Dominio")
                        .HasColumnType("integer");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Dominio");

                    b.HasIndex("PadreId_Dominio");

                    b.ToTable("Dominios");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Permisos", b =>
                {
                    b.Property<int>("Id_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Permiso"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Permiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_Permisos", b =>
                {
                    b.Property<int>("Id_Rol_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol_Permiso"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Permiso")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<int>("PermisoId_Permiso")
                        .HasColumnType("integer");

                    b.Property<int>("RolId_Rol")
                        .HasColumnType("integer");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Rol_Permiso");

                    b.HasIndex("PermisoId_Permiso");

                    b.HasIndex("RolId_Rol");

                    b.ToTable("Roles_Permisos");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_User", b =>
                {
                    b.Property<int>("Id_Roles_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Roles_User"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<int>("RolId_Rol")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId_Usuario")
                        .HasColumnType("integer");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Roles_User");

                    b.HasIndex("RolId_Rol");

                    b.HasIndex("UsuarioId_Usuario");

                    b.ToTable("Roles_User");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("E_Mail")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Auditoria", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Usuarios", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("UsuarioCreaId_Usuario");

                    b.HasOne("Plantilla_Base.Models.Administracion.Usuarios", "UsuarioModifica")
                        .WithMany()
                        .HasForeignKey("UsuarioModificaId_Usuario");

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModifica");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Dominios", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Dominios", "Padre")
                        .WithMany()
                        .HasForeignKey("PadreId_Dominio");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_Permisos", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Permisos", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId_Permiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantilla_Base.Models.Administracion.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_User", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantilla_Base.Models.Administracion.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
