// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plantilla_Base.Data;

#nullable disable

namespace Plantilla_Base.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708150125_SeguridadInicial")]
    partial class SeguridadInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Auditoria", b =>
                {
                    b.Property<int>("Id_Auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Auditoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Auditoria");

                    b.HasIndex("Id_Usuario_Creacion");

                    b.HasIndex("Id_Usuario_Modifica");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Dominios", b =>
                {
                    b.Property<int>("Id_Dominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Dominio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Padre")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Crea")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Dominio");

                    b.HasIndex("Id_Padre");

                    b.ToTable("Dominios");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Permisos", b =>
                {
                    b.Property<int>("Id_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Permiso"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Permiso");

                    b.HasIndex("Modulo", "Accion")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Rol");

                    b.HasIndex("Rol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_Permisos", b =>
                {
                    b.Property<int>("Id_Rol_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol_Permiso"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Permiso")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Rol_Permiso");

                    b.HasIndex("Id_Permiso");

                    b.HasIndex("Id_Rol", "Id_Permiso")
                        .IsUnique();

                    b.ToTable("Roles_Permisos");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_User", b =>
                {
                    b.Property<int>("Id_Roles_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Roles_User"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Roles_User");

                    b.HasIndex("Id_Rol");

                    b.HasIndex("Id_Usuario", "Id_Rol")
                        .IsUnique();

                    b.ToTable("Roles_User");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("E_Mail")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("E_Mail")
                        .IsUnique();

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Auditoria", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Usuarios", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("Id_Usuario_Creacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Plantilla_Base.Models.Administracion.Usuarios", "UsuarioModifica")
                        .WithMany()
                        .HasForeignKey("Id_Usuario_Modifica")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModifica");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Dominios", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Dominios", "Padre")
                        .WithMany()
                        .HasForeignKey("Id_Padre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_Permisos", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Permisos", "Permiso")
                        .WithMany()
                        .HasForeignKey("Id_Permiso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plantilla_Base.Models.Administracion.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Plantilla_Base.Models.Administracion.Roles_User", b =>
                {
                    b.HasOne("Plantilla_Base.Models.Administracion.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Plantilla_Base.Models.Administracion.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
